apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-hello-world
  template:
    metadata:
      labels:
        app: nodejs-hello-world
    spec:
      containers:
      - image: heroku/nodejs-hello-world
        name: nodejs-hello-world
        ports:
        - containerPort: 80